// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	conductrpc "0chain.net/conductor/conductrpc"
	mock "github.com/stretchr/testify/mock"
)

// UpdateStateFunc is an autogenerated mock type for the UpdateStateFunc type
type UpdateStateFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: state
func (_m *UpdateStateFunc) Execute(state *conductrpc.State) {
	_m.Called(state)
}
