// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	block "0chain.net/chaincore/block"

	httpclientutil "0chain.net/chaincore/httpclientutil"

	mock "github.com/stretchr/testify/mock"
)

// SmartContractFunctions is an autogenerated mock type for the SmartContractFunctions type
type SmartContractFunctions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, lfb, lfmb, isActive
func (_m *SmartContractFunctions) Execute(ctx context.Context, lfb *block.Block, lfmb *block.MagicBlock, isActive bool) (*httpclientutil.Transaction, error) {
	ret := _m.Called(ctx, lfb, lfmb, isActive)

	var r0 *httpclientutil.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, *block.Block, *block.MagicBlock, bool) *httpclientutil.Transaction); ok {
		r0 = rf(ctx, lfb, lfmb, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*httpclientutil.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *block.Block, *block.MagicBlock, bool) error); ok {
		r1 = rf(ctx, lfb, lfmb, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
