// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	util "0chain.net/core/util"
)

// DeserializerI is an autogenerated mock type for the DeserializerI type
type DeserializerI struct {
	mock.Mock
}

// Deserialize provides a mock function with given fields: sv
func (_m *DeserializerI) Deserialize(sv util.Serializable) util.Serializable {
	ret := _m.Called(sv)

	var r0 util.Serializable
	if rf, ok := ret.Get(0).(func(util.Serializable) util.Serializable); ok {
		r0 = rf(sv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(util.Serializable)
		}
	}

	return r0
}
