// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	util "0chain.net/core/util"
	mock "github.com/stretchr/testify/mock"
)

// MPTIteratorHandler is an autogenerated mock type for the MPTIteratorHandler type
type MPTIteratorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, path, key, node
func (_m *MPTIteratorHandler) Execute(ctx context.Context, path util.Path, key util.Key, node util.Node) error {
	ret := _m.Called(ctx, path, key, node)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, util.Path, util.Key, util.Node) error); ok {
		r0 = rf(ctx, path, key, node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
