// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	util "0chain.net/core/util"
	mock "github.com/stretchr/testify/mock"
)

// NodeDBIteratorHandler is an autogenerated mock type for the NodeDBIteratorHandler type
type NodeDBIteratorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, key, node
func (_m *NodeDBIteratorHandler) Execute(ctx context.Context, key util.Key, node util.Node) error {
	ret := _m.Called(ctx, key, node)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, util.Key, util.Node) error); ok {
		r0 = rf(ctx, key, node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
