// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	state "0chain.net/chaincore/chain/state"
	mock "github.com/stretchr/testify/mock"
)

// initPartitionFunc is an autogenerated mock type for the initPartitionFunc type
type initPartitionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *initPartitionFunc) Execute(_a0 state.StateContextI) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(state.StateContextI) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewInitPartitionFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newInitPartitionFunc creates a new instance of initPartitionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newInitPartitionFunc(t mockConstructorTestingTnewInitPartitionFunc) *initPartitionFunc {
	mock := &initPartitionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
