// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	minersc "0chain.net/smartcontract/minersc"
	mock "github.com/stretchr/testify/mock"

	state "0chain.net/chaincore/chain/state"
)

// movePhaseFunctions is an autogenerated mock type for the movePhaseFunctions type
type movePhaseFunctions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: balances, pn, gn
func (_m *movePhaseFunctions) Execute(balances state.StateContextI, pn *minersc.PhaseNode, gn *minersc.GlobalNode) error {
	ret := _m.Called(balances, pn, gn)

	var r0 error
	if rf, ok := ret.Get(0).(func(state.StateContextI, *minersc.PhaseNode, *minersc.GlobalNode) error); ok {
		r0 = rf(balances, pn, gn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMovePhaseFunctions interface {
	mock.TestingT
	Cleanup(func())
}

// newMovePhaseFunctions creates a new instance of movePhaseFunctions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMovePhaseFunctions(t mockConstructorTestingTnewMovePhaseFunctions) *movePhaseFunctions {
	mock := &movePhaseFunctions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
