// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PartitionItem is an autogenerated mock type for the PartitionItem type
type PartitionItem struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *PartitionItem) GetID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MarshalMsg provides a mock function with given fields: _a0
func (_m *PartitionItem) MarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Msgsize provides a mock function with given fields:
func (_m *PartitionItem) Msgsize() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UnmarshalMsg provides a mock function with given fields: _a0
func (_m *PartitionItem) UnmarshalMsg(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPartitionItem interface {
	mock.TestingT
	Cleanup(func())
}

// NewPartitionItem creates a new instance of PartitionItem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPartitionItem(t mockConstructorTestingTNewPartitionItem) *PartitionItem {
	mock := &PartitionItem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
