/*
 * 0chain Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Client struct {

	Clientid string `json:"clientid,omitempty"`

	PublicKey string `json:"public_key,omitempty"`
}
