/*
 * 0chain Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Transaction struct {

	Clientid string `json:"clientid,omitempty"`

	TransactionData string `json:"transaction_data,omitempty"`

	Createdate string `json:"createdate,omitempty"`

	Hash string `json:"hash,omitempty"`

	Signature string `json:"signature,omitempty"`
}
