// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Chainer is an autogenerated mock type for the Chainer type
type Chainer struct {
	mock.Mock
}

// IsBlockSyncing provides a mock function with given fields:
func (_m *Chainer) IsBlockSyncing() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RejectNotarizedBlock provides a mock function with given fields: hash
func (_m *Chainer) RejectNotarizedBlock(hash string) bool {
	ret := _m.Called(hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewChainer interface {
	mock.TestingT
	Cleanup(func())
}

// NewChainer creates a new instance of Chainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChainer(t mockConstructorTestingTNewChainer) *Chainer {
	mock := &Chainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
