// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	common "0chain.net/core/common"
	mock "github.com/stretchr/testify/mock"
)

// GetNow is an autogenerated mock type for the GetNow type
type GetNow struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *GetNow) Execute() common.Timestamp {
	ret := _m.Called()

	var r0 common.Timestamp
	if rf, ok := ret.Get(0).(func() common.Timestamp); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(common.Timestamp)
	}

	return r0
}

type mockConstructorTestingTNewGetNow interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetNow creates a new instance of GetNow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetNow(t mockConstructorTestingTNewGetNow) *GetNow {
	mock := &GetNow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
