// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	chain "0chain.net/chaincore/chain"
	mock "github.com/stretchr/testify/mock"
)

// MagicBlockSaver is an autogenerated mock type for the MagicBlockSaver type
type MagicBlockSaver struct {
	mock.Mock
}

// SaveMagicBlock provides a mock function with given fields:
func (_m *MagicBlockSaver) SaveMagicBlock() chain.MagicBlockSaveFunc {
	ret := _m.Called()

	var r0 chain.MagicBlockSaveFunc
	if rf, ok := ret.Get(0).(func() chain.MagicBlockSaveFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chain.MagicBlockSaveFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewMagicBlockSaver interface {
	mock.TestingT
	Cleanup(func())
}

// NewMagicBlockSaver creates a new instance of MagicBlockSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMagicBlockSaver(t mockConstructorTestingTNewMagicBlockSaver) *MagicBlockSaver {
	mock := &MagicBlockSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
