// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SenderValidateFunc is an autogenerated mock type for the SenderValidateFunc type
type SenderValidateFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *SenderValidateFunc) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSenderValidateFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewSenderValidateFunc creates a new instance of SenderValidateFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSenderValidateFunc(t mockConstructorTestingTNewSenderValidateFunc) *SenderValidateFunc {
	mock := &SenderValidateFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
