// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"

	blockdb "0chain.net/sharder/blockdb"

	mock "github.com/stretchr/testify/mock"
)

// DBIteratorHandler is an autogenerated mock type for the DBIteratorHandler type
type DBIteratorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, record
func (_m *DBIteratorHandler) Execute(ctx context.Context, record blockdb.Record) error {
	ret := _m.Called(ctx, record)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, blockdb.Record) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDBIteratorHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewDBIteratorHandler creates a new instance of DBIteratorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDBIteratorHandler(t mockConstructorTestingTNewDBIteratorHandler) *DBIteratorHandler {
	mock := &DBIteratorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
