// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	io "io"

	blockdb "0chain.net/sharder/blockdb"

	mock "github.com/stretchr/testify/mock"
)

// Record is an autogenerated mock type for the Record type
type Record struct {
	mock.Mock
}

// Decode provides a mock function with given fields: reader
func (_m *Record) Decode(reader io.Reader) error {
	ret := _m.Called(reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = rf(reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Encode provides a mock function with given fields: writer
func (_m *Record) Encode(writer io.Writer) error {
	ret := _m.Called(writer)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = rf(writer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetKey provides a mock function with given fields:
func (_m *Record) GetKey() blockdb.Key {
	ret := _m.Called()

	var r0 blockdb.Key
	if rf, ok := ret.Get(0).(func() blockdb.Key); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(blockdb.Key)
	}

	return r0
}

type mockConstructorTestingTNewRecord interface {
	mock.TestingT
	Cleanup(func())
}

// NewRecord creates a new instance of Record. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRecord(t mockConstructorTestingTNewRecord) *Record {
	mock := &Record{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
