version: '3'
services:
  magicblock:
    image: "magic-block"
    environment:
      - DOCKER=true

    volumes:
      - ../config/magicBlock:/config

    command: ./bin/magicBlock --mainnet --config_file nodes
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
