// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	block "0chain.net/chaincore/block"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AfterFetcher is an autogenerated mock type for the AfterFetcher type
type AfterFetcher struct {
	mock.Mock
}

// AfterFetch provides a mock function with given fields: ctx, b
func (_m *AfterFetcher) AfterFetch(ctx context.Context, b *block.Block) error {
	ret := _m.Called(ctx, b)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *block.Block) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
