// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	block "0chain.net/chaincore/block"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MagicBlockSaveFunc is an autogenerated mock type for the MagicBlockSaveFunc type
type MagicBlockSaveFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MagicBlockSaveFunc) Execute(_a0 context.Context, _a1 *block.Block) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *block.Block) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
