// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	chain "0chain.net/chaincore/chain"
	mock "github.com/stretchr/testify/mock"
)

// MagicBlockSaver is an autogenerated mock type for the MagicBlockSaver type
type MagicBlockSaver struct {
	mock.Mock
}

// SaveMagicBlock provides a mock function with given fields:
func (_m *MagicBlockSaver) SaveMagicBlock() chain.MagicBlockSaveFunc {
	ret := _m.Called()

	var r0 chain.MagicBlockSaveFunc
	if rf, ok := ret.Get(0).(func() chain.MagicBlockSaveFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chain.MagicBlockSaveFunc)
		}
	}

	return r0
}
