// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	datastore "0chain.net/core/datastore"
	mock "github.com/stretchr/testify/mock"

	node "0chain.net/chaincore/node"

	url "net/url"
)

// EntityRequestor is an autogenerated mock type for the EntityRequestor type
type EntityRequestor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: urlParams, handler
func (_m *EntityRequestor) Execute(urlParams *url.Values, handler datastore.JSONEntityReqResponderF) node.SendHandler {
	ret := _m.Called(urlParams, handler)

	var r0 node.SendHandler
	if rf, ok := ret.Get(0).(func(*url.Values, datastore.JSONEntityReqResponderF) node.SendHandler); ok {
		r0 = rf(urlParams, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node.SendHandler)
		}
	}

	return r0
}
