// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BatchI is an autogenerated mock type for the BatchI type
type BatchI struct {
	mock.Mock
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *BatchI) Query(_a0 string, _a1 ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	_m.Called(_ca...)
}
