// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	storagesc "0chain.net/smartcontract/storagesc"
	mock "github.com/stretchr/testify/mock"
)

// filterBlobberFunc is an autogenerated mock type for the filterBlobberFunc type
type filterBlobberFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: blobber
func (_m *filterBlobberFunc) Execute(blobber *storagesc.StorageNode) bool {
	ret := _m.Called(blobber)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*storagesc.StorageNode) bool); ok {
		r0 = rf(blobber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
