CREATE TABLE IF NOT EXISTS zerochain.txn_summary (
hash text PRIMARY KEY,
round bigint
);
CREATE MATERIALIZED VIEW ZEROCHAIN.ROUND_TO_HASH IF NOT EXISTS AS SELECT ROUND, HASH FROM zerochain.txn_summary WHERE ROUND IS NOT NULL PRIMARY KEY (ROUND, HASH);