package storagesc

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *BlobberOfferStake) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "o"
	o = append(o, 0x83, 0xa1, 0x6f)
	o, err = z.TotalOffers.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "TotalOffers")
		return
	}
	// string "s"
	o = append(o, 0xa1, 0x73)
	o, err = z.TotalStake.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "TotalStake")
		return
	}
	// string "a"
	o = append(o, 0xa1, 0x61)
	o = msgp.AppendInt64(o, z.Allocated)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BlobberOfferStake) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "o":
			bts, err = z.TotalOffers.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalOffers")
				return
			}
		case "s":
			bts, err = z.TotalStake.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalStake")
				return
			}
		case "a":
			z.Allocated, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Allocated")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BlobberOfferStake) Msgsize() (s int) {
	s = 1 + 2 + z.TotalOffers.Msgsize() + 2 + z.TotalStake.Msgsize() + 2 + msgp.Int64Size
	return
}

// MarshalMsg implements msgp.Marshaler
func (z BlobberOfferStakeList) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for za0001 := range z {
		if z[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			// map header, size 3
			// string "o"
			o = append(o, 0x83, 0xa1, 0x6f)
			o, err = z[za0001].TotalOffers.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, za0001, "TotalOffers")
				return
			}
			// string "s"
			o = append(o, 0xa1, 0x73)
			o, err = z[za0001].TotalStake.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, za0001, "TotalStake")
				return
			}
			// string "a"
			o = append(o, 0xa1, 0x61)
			o = msgp.AppendInt64(o, z[za0001].Allocated)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BlobberOfferStakeList) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(BlobberOfferStakeList, zb0002)
	}
	for zb0001 := range *z {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			(*z)[zb0001] = nil
		} else {
			if (*z)[zb0001] == nil {
				(*z)[zb0001] = new(BlobberOfferStake)
			}
			var field []byte
			_ = field
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			for zb0003 > 0 {
				zb0003--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
				switch msgp.UnsafeString(field) {
				case "o":
					bts, err = (*z)[zb0001].TotalOffers.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, zb0001, "TotalOffers")
						return
					}
				case "s":
					bts, err = (*z)[zb0001].TotalStake.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, zb0001, "TotalStake")
						return
					}
				case "a":
					(*z)[zb0001].Allocated, bts, err = msgp.ReadInt64Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, zb0001, "Allocated")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, zb0001)
						return
					}
				}
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z BlobberOfferStakeList) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0004 := range z {
		if z[zb0004] == nil {
			s += msgp.NilSize
		} else {
			s += 1 + 2 + z[zb0004].TotalOffers.Msgsize() + 2 + z[zb0004].TotalStake.Msgsize() + 2 + msgp.Int64Size
		}
	}
	return
}
