name: Mirror repo to S3 (weekly)

on:
  schedule:
    # Runs every Monday at 12:25 AM UTC
    - cron: '25 0 * * 1'
  workflow_dispatch:

jobs:
  s3Backup:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Get commit date info
        id: get_info
        run: |
          GIT_COMMIT_DATE=$(git log -1 --date=format:%d --pretty=format:%d)
          YESTERDAY_DATE=$(date -d "yesterday" '+%d')
          echo "GIT_COMMIT_DATE=$GIT_COMMIT_DATE" >> $GITHUB_ENV
          echo "YESTERDAY_DATE=$YESTERDAY_DATE" >> $GITHUB_ENV
          echo "Git commit day: $GIT_COMMIT_DATE"
          echo "Yesterday: $YESTERDAY_DATE"


      - name: Ensure AWS CLI is installed
        run: |
          if ! command -v aws &> /dev/null
          then
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI already installed. Skipping installation."
            aws --version
          fi
          aws --version || { echo "AWS CLI installation failed"; exit 1; }


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip zip
          pip install github-backup


      - name: Create backup
        run: |
          mkdir -p /github-backup/0chain
          github-backup -O 0chain -P -t "${{ secrets.SVC_ACCOUNT_SECRET }}" \
            --output-directory=/github-backup/0chain --all -O -R 0chain


      - name: Create zip
        run: zip -r 0chain.zip /github-backup/0chain


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.BACKUP_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BACKUP_SECRET_KEY_ID }}
          aws-region: us-east-2

      - name: Upload backup to S3
        run: aws s3 cp 0chain.zip s3://${{ secrets.MIRROR_TARGET }}/0chain.zip
