// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HashScorer is an autogenerated mock type for the HashScorer type
type HashScorer struct {
	mock.Mock
}

// Score provides a mock function with given fields: hash1, hash2
func (_m *HashScorer) Score(hash1 []byte, hash2 []byte) int32 {
	ret := _m.Called(hash1, hash2)

	var r0 int32
	if rf, ok := ret.Get(0).(func([]byte, []byte) int32); ok {
		r0 = rf(hash1, hash2)
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

type mockConstructorTestingTNewHashScorer interface {
	mock.TestingT
	Cleanup(func())
}

// NewHashScorer creates a new instance of HashScorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHashScorer(t mockConstructorTestingTNewHashScorer) *HashScorer {
	mock := &HashScorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
