// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// JSONReqResponderF is an autogenerated mock type for the JSONReqResponderF type
type JSONReqResponderF struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, json
func (_m *JSONReqResponderF) Execute(ctx context.Context, json map[string]interface{}) (interface{}, error) {
	ret := _m.Called(ctx, json)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) interface{}); ok {
		r0 = rf(ctx, json)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, json)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJSONReqResponderF interface {
	mock.TestingT
	Cleanup(func())
}

// NewJSONReqResponderF creates a new instance of JSONReqResponderF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJSONReqResponderF(t mockConstructorTestingTNewJSONReqResponderF) *JSONReqResponderF {
	mock := &JSONReqResponderF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
