// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ReqRespHandlerf is an autogenerated mock type for the ReqRespHandlerf type
type ReqRespHandlerf struct {
	mock.Mock
}

// Execute provides a mock function with given fields: w, r
func (_m *ReqRespHandlerf) Execute(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

type mockConstructorTestingTNewReqRespHandlerf interface {
	mock.TestingT
	Cleanup(func())
}

// NewReqRespHandlerf creates a new instance of ReqRespHandlerf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReqRespHandlerf(t mockConstructorTestingTNewReqRespHandlerf) *ReqRespHandlerf {
	mock := &ReqRespHandlerf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
